### ISSUE TITLE
driver remove without an argument segfaults

### ISSUE THREAD

**Issue by vmarkovtsev** [bblfsh/bblfshd#232]
```
$ bblfshctl driver remove
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xbaea12]

goroutine 1 [running]:
github.com/bblfsh/bblfshd/cmd/bblfshctl/cmd.(*DriverRemoveCommand).Execute(0xc420097a90, 0xc42017f600, 0x0, 0x2, 0xc420097a90, 0x1)
	/go/src/github.com/bblfsh/bblfshd/cmd/bblfshctl/cmd/driver_remove.go:52 +0x1c2
github.com/bblfsh/bblfshd/vendor/github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc420258060, 0xc420030100, 0x2, 0x2, 0x2, 0x4, 0xc4203ca6c0, 0xc420454f00, 0xc420454dc8)
	/go/src/github.com/bblfsh/bblfshd/vendor/github.com/jessevdk/go-flags/parser.go:316 +0x80b
github.com/bblfsh/bblfshd/vendor/github.com/jessevdk/go-flags.(*Parser).Parse(0xc420258060, 0xe1a1f2, 0x6, 0xf0f7ac, 0x2d, 0xf0f7ac)
	/go/src/github.com/bblfsh/bblfshd/vendor/github.com/jessevdk/go-flags/parser.go:186 +0x71
main.main()
	/go/src/github.com/bblfsh/bblfshd/cmd/bblfshctl/main.go:57 +0x448
```

**Comment by dennwc** [comment]
Was fixed two months ago in cd80a49a24bd4155fcbe76901abc59660863bae2.
